[tools]
hyperfine = "1.20.0"
jsonschema = "14.20.2"
node = "24.15.0"
yarn = "4.14.0"

[tasks."generate:schemas"]
run = "node ./scripts/generate-schemas.ts"
[tasks."generate:types"]
run = "node ./scripts/generate-types.ts"
[tasks.generate]
depends = ["generate:*"]

[tasks."test:schemas"]
run = "jsonschema test schemas/__tests__/*.test.json"
