[tools]
hyperfine = "1.20.0"
jsonschema = "14.17.1"
node = "24.14.1"
yarn = "4.13.0"

[tasks."generate:schemas"]
run = "node ./scripts/generate-schemas.ts"
[tasks."generate:types"]
run = "node ./scripts/generate-types.ts"
[tasks.generate]
depends = ["generate:*"]

[tasks."test:schemas"]
run = "jsonschema test schemas/__tests__/*.test.json"
