export { CompatTypeScript } from "./CompatTypeScript.js";
export { NativeTypeScript } from "./NativeTypeScript.js";
export type {
  CallExpression,
  CommentRange,
  Decorator,
  Diagnostic,
  DiagnosticLocation,
  DiagnosticPosition,
  Expression,
  ImportDeclaration,
  LiteralType,
  Node,
  NodeArray,
  NumberLiteralType,
  NumericLiteral,
  PropertyAccessExpression,
  PropertyDeclaration,
  RegularExpressionLiteral,
  SourceFile,
  StringLiteralLikeNode,
  StringLiteralType,
  TupleTypeNode,
  Type,
  TypeNode,
  TypeScript,
} from "./types.js";
