name: Benchmarks

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  benchmarks:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
      - run: aube ci
      - run: aube run build
      - run: mise run bench

      - uses: bencherdev/bencher@50fb1e138651a46d2fb704fab1adab38c181552e # v0.6.6
      - name: Run bencher
        run: |
          bencher run \
          --adapter 'shell_hyperfine' \
          --file 'benchmark/results.json' \
          --project 'tstyche' \
          --token "${{ secrets.BENCHER_TOKEN }}"
