name: Benchmarks

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  benchmarks:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - run: aube ci
      - run: aube run build
      - run: mise run bench

      - uses: bencherdev/bencher@50fb1e138651a46d2fb704fab1adab38c181552e # main
      - name: Run bencher
        run: |
          bencher run \
          --adapter 'shell_hyperfine' \
          --file 'benchmark/results.json' \
          --project 'tstyche' \
          --token "${{ secrets.BENCHER_TOKEN }}"
