name: Benchmarks

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  benchmarks:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      - run: aube ci
      - run: aube run build
      - run: mise run bench

      - uses: bencherdev/bencher@8d75325c3bc59403a2186a056b472c4f49d42838 # v0.6.12
      - name: Run bencher
        run: |
          bencher run \
          --adapter 'shell_hyperfine' \
          --file 'benchmark/results.json' \
          --project 'tstyche' \
          --token "${{ secrets.BENCHER_TOKEN }}"
