name: TypeScript's Nightly

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  check-types:
    name: Check Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - run: yarn install
      - run: yarn build
      - run: yarn dlx --package typescript@next tsc --build --force --verbose

  test-types:
    name: Test Types
    # TODO enable after adding support for TypeScript 7
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - run: yarn install
      - run: yarn build
      - run: yarn test:types --target next
      - run: yarn test:examples --target next
