name: Publish

permissions:
  contents: read
  id-token: write

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          cache: false
      - run: aube ci
      - run: aube run build

      - run: jaq -i 'del(.scripts, .devDependencies)' package.json

      - run: |
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            aube publish --access public --no-git-checks --provenance --tag next
          else
            aube publish --access public --no-git-checks --provenance
          fi
