name: Publish

permissions:
  contents: read
  id-token: write

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
        with:
          cache: false
      - run: aube ci
      - run: aube run build

      - run: jaq -i 'del(.scripts, .devDependencies)' package.json

      - run: |
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            aube publish --access public --no-git-checks --provenance --tag next
          else
            aube publish --access public --no-git-checks --provenance
          fi
